### ISSUE TITLE
[Enhancement] Add implicit deletion function

### ISSUE THREAD

**Issue by flkhndlr** [telekom-mms/ansible-collection-icinga-director#231]
### Description

You currently need to explicitly state the Icinga Director Objects you want to delete. We encountered several situations, where a object was deleted as code, but not removed. The reason is, that you need to state them as a deletion office.
A solution could be to implicitly delete the Objects when removed in Ansible

We came up with following solution as a playbook:
```
---
- hosts: localhost
  gather_facts: false
  collections:
    - t_systems_mms.icinga_director
  tasks:
    - name: include Vars
      ansible.builtin.include_vars:
        file: vars/icinga_service.yml

    - name: get all object configs
      telekom_mms.icinga_director.icinga_service_info:
        url: "{{ icinga_host }}"
        url_username: "{{ icinga_user }}"
        url_password: "{{ icinga_pass }}"
        query: "*"
        force_basic_auth: true
      register: result

    - name: create objects scheduled for deletion
      set_fact:
        icinga_services: "{{ icinga_services + [{'service_object': [item.object_name], 'state': 'absent' }] }}"
      when: not icinga_services|selectattr('service_object', 'contains', item.object_name)
      loop: "{{ result.objects }}"

  roles:
    - ansible_icinga
  vars:
    icinga_force_basic_auth: true

```

Is there a way to include this either into the collection as an example or create a solution in the role or modules itself?
Thanks in advance!
