### ISSUE TITLE
[Bug] Changes are reported in Icinga Activity log when nothing is different

### ISSUE THREAD

**Issue by flkhndlr** [telekom-mms/ansible-collection-icinga-director#246]
### Description

When rolling out the config with the collection Icinga shows changes in all object types (like commands or hostgroups). No changes to the config were made though and the rendered config is the same, too. This behavior is consistent over multiple runs. The objects shown in the diff inside the activity log are not there.

### Reproduction steps

1. Rollout multiple Objects with multiple commands, timeperiods, hostgroups, hosttemplates etc.
2. Render config
3. See Changes in activitiy log (new object, former object)

### Current Behavior

Changes are reported in the activity log, but diff is non

### Expected Behavior

No Changes in the activity log

**Comment by rndmh3ro** [comment]
Can you please provide the used versions of the collection, icinga and the icinga-director?

Also, do you have a minimal reproduction case?

**Comment by schurzi** [comment]
Minimal reproduction case for the `icinga_user` module:

Run local image with director 1.9.1.: `docker run -p 8080:80 ghcr.io/t-systems-mms/icinga2:director-1.9.1`

```yaml
- hosts: localhost
  tasks:
  - name: Create timeperiod
    telekom_mms.icinga_director.icinga_timeperiod:
      state: present
      url: "http://localhost:8080/icingaweb2"
      url_username: "icingaadmin"
      url_password: "icinga"
      object_name: '24/7'
      ranges:
        monday: "00:00-23:59"
        tuesday: "00:00-23:59"
        wednesday: "00:00-23:59"
        thursday: "00:00-23:59"
        friday: "00:00-23:59"
        saturday: "00:00-23:59"
        sunday: "00:00-23:59"
  - name: Create user template
    telekom_mms.icinga_director.icinga_user_template:
      state: present
      url: "http://localhost:8080/icingaweb2"
      url_username: "icingaadmin"
      url_password: "icinga"
      object_name: "domon-user"
      enable_notifications: false
      period: '24/7'
  - name: Create user
    telekom_mms.icinga_director.icinga_user:
      state: present
      url: "http://localhost:8080/icingaweb2"
      url_username: "icingaadmin"
      url_password: "icinga"
      object_name: "rb"
      imports: domon-user
      display_name: "Rufbereitschaft_24x7"
      email: "alerts@mms-support.de"
      period: "24/7"
```

THis will always show changes für the user and the user template.
