### ISSUE TITLE
Mistyping variables in the role does not throw an error

### ISSUE THREAD

**Issue by rndmh3ro** [telekom-mms/ansible-collection-icinga-director#34]
If you use the role and write a play with a typo in it, the playbook will not throw an error:

```
- hosts: localhost
  gather_facts: false
  collections:
  - t_systems_mms.icinga_director
  roles:
    - ansible_icinga
  vars:
    icinga_url: "{{ icinga_host }}"
    icinga_user: "{{ icinga_username }}"
    icinga_pass: "{{ icinga_password }}"
    icinga_force_basic_auth: true

    icinga_hosts:
      - host_object:
          - "customer-live-services"
        address: "127.0.0.1"
        imorts:                                              # typo here, missing "p"
          - "empty-hosts"
```

This can also happen with other variables like `address`. This can lead to undefined or wrong behaviour and is not noticeable trough Ansible - you have to check Icinga for this.

**Comment by rndmh3ro** [comment]
This is fixed with version 2.0.0:

```
- hosts: localhost
  gather_facts: false
  collections:
  - telekom_mms.icinga_director
  roles:
    - ansible_icinga
  vars:
    icinga_url: "{{ icinga_host }}"
    icinga_user: "{{ icinga_username }}"
    icinga_pass: "{{ icinga_password }}"
    icinga_force_basic_auth: true

    icinga_hosts:
      - name: "customer-live-services"
        address: "127.0.0.1"
        imorts:                                              # typo here, missing "p"
          - "empty-hosts"

```

results in:

```
failed: [localhost] (item={'name': 'customer-live-services', 'address': '127.0.0.1', 'imorts': ['empty-hosts']}) => {"ansible_loop_var": "host", "attempts": 3, "changed": false, "host": {"address": "127.0.0.1", "imorts": ["empty-hosts"], "name": "customer-live-services"}, "msg": "missing required arguments: imports."}

```
